fwdis:
  WHEEL_RADIUS: 0.100 #[m]
  WHEEL_BASE: 0.400 #[m]
  TREAD: 0.400 #[m]
  MAX_WHEEL_ANGULAR_VELOCITY: 30 #[rad/s]
  MAX_WHEEL_ANGULAR_ACCELERATION: 60 #[rad/ss]
  MAX_STEERING_ANGLE: 2.094395 #[rad] # 120[deg]
